/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package store.ui;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import store.dao.impl.ChiTietSanPhamDAOImpl;
import store.dao.impl.HoaDonChiTietDAOimpl;
import store.dao.impl.ImeiDAOimpl;
import store.dao.impl.ImeiDaBanDAOimpl;
import store.entity.ChiTietSanPham;
import store.entity.HoaDonChiTiet;
import store.entity.ImeiDaBan;

/**
 *
 * @author dell
 */
public class ImeiDaBanJdialog extends javax.swing.JDialog {

    /**
     * Creates new form ImeiDaBanJdilog
     */List<ImeiDaBan> lstImeiDaBan = new ArrayList<>();
    ImeiDaBanDAOimpl imeiDaBanDAOimpl = new ImeiDaBanDAOimpl();
    ImeiDAOimpl imeiDao = new ImeiDAOimpl();
    HoaDonChiTietDAOimpl hdctDao = new HoaDonChiTietDAOimpl();
    ChiTietSanPhamDAOImpl chiTIetSanPhamDAO = new ChiTietSanPhamDAOImpl();
  
    private int idHoaDonCThehe;
    
    public ImeiDaBanJdialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocation(900, 270);
    }
    
     public void fillToImei(int idHoaDonCT) {
        DefaultTableModel model = (DefaultTableModel) tblImei.getModel();
        model.setRowCount(0);
        lstImeiDaBan = imeiDaBanDAOimpl.findOne(idHoaDonCT);
        for (ImeiDaBan imeiDaBan : lstImeiDaBan) {
            Object[] row = {
                imeiDaBan.getMaImei()
            };
            model.addRow(row);
        }
        idHoaDonCThehe = idHoaDonCT;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        tblImei = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblImei.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Imei"
            }
        ));
        jScrollPane3.setViewportView(tblImei);

        jButton1.setText("Bỏ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(105, 105, 105))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int index = tblImei.getSelectedRow();
                if (index < 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn mã imei muốn bỏ", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
                int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc là muốn bỏ imei này ?");
        if (confirm == JOptionPane.YES_OPTION) {
        String maImei = (String) tblImei.getValueAt(index, 0);
        HoaDonChiTiet hdct = hdctDao.findOne(idHoaDonCThehe);
        ChiTietSanPham ctsp = chiTIetSanPhamDAO.findOne(hdct.getIdSanPham());
        hdct.setSoLuong(hdct.getSoLuong() - 1);
        hdct.setGia(hdct.getGia().subtract(ctsp.getGia())); 
        hdctDao.update2(hdct);
        imeiDao.avilable1(maImei);
        imeiDaBanDAOimpl.delete2(maImei);
        chiTIetSanPhamDAO.changeAvailable2(hdct.getIdSanPham());
        
        fillToImei(idHoaDonCThehe);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImeiDaBanJdialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImeiDaBanJdialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImeiDaBanJdialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImeiDaBanJdialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ImeiDaBanJdialog dialog = new ImeiDaBanJdialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblImei;
    // End of variables declaration//GEN-END:variables
}
