/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package store.ui;

import java.util.ArrayList;
import java.util.List;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import store.controller.NhanVienController;
import store.dao.impl.NhanVienDAOimpl;
import store.entity.NhanVien;

public class ViewNhanVien extends javax.swing.JPanel implements NhanVienController {

    List<NhanVien> lstNhanVien = new ArrayList<>();
    NhanVienDAOimpl nhanVienDAO = new NhanVienDAOimpl();
    private static final Pattern VN_PHONE = Pattern.compile("^0\\d{9}$");
    
    public static boolean isValidVNPhone(String phone) {
        return VN_PHONE.matcher(phone).matches();
    }
    
    private static final Pattern EMAIL_PATTERN = Pattern.compile(
        "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$"
    );

    public static boolean isValidEmail(String email) {
        return EMAIL_PATTERN.matcher(email).matches();
    }

    public ViewNhanVien() {
        initComponents();
        fillToTable();
        txtID.setEditable(false);
    }

    private void fillForm(int index) {
        lstNhanVien = nhanVienDAO.findAll();
        NhanVien entity = lstNhanVien.get(index);
        txtMaNV.setText(entity.getMaNV());
        txtSoDienThoai.setText(entity.getSdt());
        txtHoTen.setText(entity.getHoTen());
        txtmatKhau.setText(entity.getMatKhau());
        if (entity.getGioiTinh() == 1) {
            rdoNam.setSelected(true);
        } else {
            rdoNu.setSelected(true);
        }
        if (entity.getChucVu() == 1) {
            rdoQuanLy.setSelected(true);
        } else {
            rdoNhanVien.setSelected(true);
        }
        txtNgaySinh.setText(entity.getNgaySinh());
        if (entity.getTrangThai() == 1) {
            rdoDangLam.setSelected(true);
        } else {
            rdoNghiLam.setSelected(true);
        }
        txtID.setText(String.valueOf(entity.getId()));
        txtEmail.setText(entity.getEmail());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        txtSoDienThoai = new javax.swing.JTextField();
        txtmatKhau = new javax.swing.JTextField();
        txtNgaySinh = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        lblTenSanPham = new javax.swing.JLabel();
        lblTenSanPham1 = new javax.swing.JLabel();
        lblTenSanPham2 = new javax.swing.JLabel();
        lblTenSanPham3 = new javax.swing.JLabel();
        lblTenSanPham4 = new javax.swing.JLabel();
        lblTenSanPham5 = new javax.swing.JLabel();
        lblTenSanPham6 = new javax.swing.JLabel();
        lblTenSanPham7 = new javax.swing.JLabel();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        rdoDangLam = new javax.swing.JRadioButton();
        rdoNghiLam = new javax.swing.JRadioButton();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        lblTenSanPham8 = new javax.swing.JLabel();
        btnXoa = new javax.swing.JButton();
        txtMaNV = new javax.swing.JTextField();
        lblTenSanPham9 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        rdoQuanLy = new javax.swing.JRadioButton();
        rdoNhanVien = new javax.swing.JRadioButton();
        txtEmail = new javax.swing.JTextField();
        lblTenSanPham10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(239, 243, 234));
        setPreferredSize(new java.awt.Dimension(1080, 720));

        jPanel3.setBackground(new java.awt.Color(128, 203, 196));
        jPanel3.setPreferredSize(new java.awt.Dimension(400, 600));

        txtSoDienThoai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtmatKhau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtNgaySinh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtHoTen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tblNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã", "Họ tên", "Giới Tính", "Ngày Sinh", "Số Điện Thoại", "Mật Khẩu ", "Chức Vụ", "Email", "Trạng Thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNhanVien.setGridColor(new java.awt.Color(128, 203, 196));
        tblNhanVien.setRowHeight(30);
        tblNhanVien.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanVienMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblNhanVien);

        lblTenSanPham.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTenSanPham.setText("Họ Và Tên:");

        lblTenSanPham1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTenSanPham1.setText("Mã Nhân Viên:");

        lblTenSanPham2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTenSanPham2.setText("Ngày Sinh:");

        lblTenSanPham3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTenSanPham3.setText("Số Điện Thoại:");

        lblTenSanPham4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTenSanPham4.setText("Giới Tính:");

        lblTenSanPham5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTenSanPham5.setText("Mật Khẩu");

        lblTenSanPham6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTenSanPham6.setText("Trạng Thái");

        lblTenSanPham7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTenSanPham7.setText("Chức Vụ");

        buttonGroup1.add(rdoNam);
        rdoNam.setText("Nam");

        buttonGroup1.add(rdoNu);
        rdoNu.setText("Nữ");

        buttonGroup2.add(rdoDangLam);
        rdoDangLam.setText("Đang Làm");

        buttonGroup2.add(rdoNghiLam);
        rdoNghiLam.setText("Nghỉ Làm");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnSearch.setText("Tìm Kiếm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblTenSanPham8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTenSanPham8.setText("Tìm kiếm:");

        btnXoa.setText("Xoá");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        txtMaNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblTenSanPham9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTenSanPham9.setText("ID");

        txtID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        buttonGroup3.add(rdoQuanLy);
        rdoQuanLy.setText("Quản lý");

        buttonGroup3.add(rdoNhanVien);
        rdoNhanVien.setText("Nhân viên");

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblTenSanPham10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTenSanPham10.setText("Email");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTenSanPham4)
                            .addComponent(lblTenSanPham)
                            .addComponent(lblTenSanPham2)
                            .addComponent(lblTenSanPham9)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblTenSanPham8)))
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(rdoNam)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rdoNu)))
                        .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblTenSanPham10)
                        .addComponent(lblTenSanPham5)
                        .addComponent(lblTenSanPham3)
                        .addComponent(lblTenSanPham7)
                        .addComponent(lblTenSanPham6))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(rdoDangLam)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rdoNghiLam))
                                    .addComponent(txtmatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSoDienThoai)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(rdoQuanLy)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rdoNhanVien)))
                                .addContainerGap(72, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(lblTenSanPham1)
                    .addContainerGap(946, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTenSanPham3)
                            .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTenSanPham)
                            .addComponent(lblTenSanPham5)
                            .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTenSanPham7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdoQuanLy)
                            .addComponent(rdoNhanVien))
                        .addGap(7, 7, 7))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTenSanPham4)
                        .addComponent(rdoNam)
                        .addComponent(rdoNu)))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenSanPham2)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTenSanPham6)
                    .addComponent(rdoDangLam)
                    .addComponent(rdoNghiLam))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTenSanPham9)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTenSanPham10))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTenSanPham8)
                                    .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))))
                        .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addComponent(lblTenSanPham1)
                    .addContainerGap(691, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1074, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanVienMouseClicked
        int index = tblNhanVien.getSelectedRow();
        fillForm(index);
    }//GEN-LAST:event_tblNhanVienMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        if (txtSearch.getText().isEmpty()) {
            fillToTable();
        } else {
            String ma = txtSearch.getText();
            List<NhanVien> lstNhanVienSearch = new ArrayList<>();
            DefaultTableModel model = (DefaultTableModel) tblNhanVien.getModel();
            model.setRowCount(0);

            // Thử tìm theo mã
            lstNhanVienSearch = nhanVienDAO.findList(ma);

            // Nếu rỗng, thử tìm theo tên
            if (lstNhanVienSearch.isEmpty()) {
                lstNhanVienSearch = nhanVienDAO.findByName(ma);
            }

            // Nếu vẫn rỗng, thử tìm theo email
            if (lstNhanVienSearch.isEmpty()) {
                lstNhanVienSearch = nhanVienDAO.findByEmail(ma);
            }

            // Nếu vẫn rỗng, thử tìm theo số điện thoại
            if (lstNhanVienSearch.isEmpty()) {
                lstNhanVienSearch = nhanVienDAO.findBySDT(ma);
            }

            // Hiển thị kết quả (nếu có)
            for (NhanVien nhanVien : lstNhanVienSearch) {
                Object[] row = {
                    nhanVien.getId(),
                    nhanVien.getMaNV(),
                    nhanVien.getHoTen(),
                    nhanVien.getGioiTinh() == 1 ? "Nam" : "Nữ",
                    nhanVien.getNgaySinh(),
                    nhanVien.getSdt(),
                    nhanVien.getMatKhau(),
                    nhanVien.getChucVu() == 1 ? "Quản lý" : "Nhân viên",
                    nhanVien.getEmail(),
                    nhanVien.getTrangThai() == 1 ? "Đang làm" : "Nghỉ làm"
                };
                model.addRow(row);
            }
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc là muốn thêm ?");
        if (confirm == JOptionPane.YES_OPTION) {

            if (txtHoTen.getText().isEmpty() || txtMaNV.getText().isEmpty() || txtNgaySinh.getText().isEmpty() || txtSoDienThoai.getText().isEmpty() || txtmatKhau.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đủ các trường!");
                return;
            }

            if (txtSoDienThoai.getText().length() < 10 || !isValidVNPhone(txtSoDienThoai.getText())) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập số điện thoại hợp lệ!");
                return;
            }
            
            if (!isValidEmail(txtEmail.getText())) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập Email hợp lệ!");
                return;
            }
            
            String ma = txtMaNV.getText();
            for (NhanVien nv : nhanVienDAO.findAll()) {
                if (nv.getMaNV().equalsIgnoreCase(ma)) {
                    JOptionPane.showMessageDialog(this, "Không được nhập mã nhân viên đã tồn tại!");
                    return;
                }
            }

            String sdt = txtSoDienThoai.getText();
            for (NhanVien nv : nhanVienDAO.findAll()) {
                if (nv.getSdt().equalsIgnoreCase(sdt)) {
                    JOptionPane.showMessageDialog(this, "Không được nhập trùng số điện thoại của nhân viên khác!");
                    return;
                }
            }
            
            String mail = txtEmail.getText();
            for (NhanVien nv : nhanVienDAO.findAll()) {
                if (nv.getEmail().equalsIgnoreCase(mail)) {
                    JOptionPane.showMessageDialog(this, "Không được nhập trùng Email của nhân viên khác!");
                    return;
                }
            }

            NhanVien entity = new NhanVien();
            entity.setMaNV(txtMaNV.getText());
            entity.setSdt(txtSoDienThoai.getText());
            entity.setHoTen(txtHoTen.getText());
            entity.setMatKhau(txtmatKhau.getText());
            if (rdoNam.isSelected()) {
                entity.setGioiTinh(1);
            } else {
                entity.setGioiTinh(0);
            }
            if (rdoQuanLy.isSelected()) {
                entity.setChucVu(1);
            } else {
                entity.setChucVu(0);
            }
            entity.setNgaySinh(txtNgaySinh.getText());
            if (rdoDangLam.isSelected()) {
                entity.setTrangThai(1);
            } else {
                entity.setTrangThai(0);
            }
            entity.setEmail(txtEmail.getText());
            nhanVienDAO.create(entity);
            fillToTable();
            JOptionPane.showMessageDialog(this, "Đã thêm thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int check = tblNhanVien.getSelectedRow();
        if (check < 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng cần xoá!");
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc là muốn xóa ?");
        if (confirm == JOptionPane.YES_OPTION) {
            String ma = txtMaNV.getText();
            try {
                nhanVienDAO.delete(ma);   // gọi DAO để xóa
                fillToTable();            // load lại bảng
                JOptionPane.showMessageDialog(this,
                        "Đã xóa thành công",
                        "Thông báo",
                        JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Xóa thất bại do đang có hoá đơn liên kết với nhân viên này!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        int check = tblNhanVien.getSelectedRow();
        if (check < 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng cần sửa!");
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc là muốn sửa ?");
        if (confirm == JOptionPane.YES_OPTION) {
            if (txtHoTen.getText().isEmpty() || txtMaNV.getText().isEmpty() || txtNgaySinh.getText().isEmpty() || txtSoDienThoai.getText().isEmpty() || txtmatKhau.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đủ các trường!");
                return;
            }

            if (txtSoDienThoai.getText().length() < 10 || !isValidVNPhone(txtSoDienThoai.getText())) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập số điện thoại hợp lệ!");
                return;
            }
            
            if (!isValidEmail(txtEmail.getText())) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập Email hợp lệ!");
                return;
            }
            
            String sdt = txtSoDienThoai.getText();
            for (NhanVien nv : nhanVienDAO.findAll()) {
                if (nv.getSdt().equalsIgnoreCase(sdt) && !txtMaNV.getText().equalsIgnoreCase(nv.getMaNV())) {
                    JOptionPane.showMessageDialog(this, "Không được nhập trùng số điện thoại của nhân viên khác!");
                    return;
                }
            }
            
            String mail = txtEmail.getText();
            for (NhanVien nv : nhanVienDAO.findAll()) {
                if (nv.getEmail().equalsIgnoreCase(mail) && !txtMaNV.getText().equalsIgnoreCase(nv.getMaNV())) {
                    JOptionPane.showMessageDialog(this, "Không được nhập trùng Email của nhân viên khác!");
                    return;
                }
            }

            NhanVien entity = new NhanVien();
            entity.setId(Integer.parseInt(txtID.getText()));
            entity.setMaNV(txtMaNV.getText());
            entity.setSdt(txtSoDienThoai.getText());
            entity.setHoTen(txtHoTen.getText());
            entity.setMatKhau(txtmatKhau.getText());
            if (rdoNam.isSelected()) {
                entity.setGioiTinh(1);
            } else {
                entity.setGioiTinh(0);
            }
            if (rdoQuanLy.isSelected()) {
                entity.setChucVu(1);
            } else {
                entity.setChucVu(0);
            }
            entity.setNgaySinh(txtNgaySinh.getText());
            if (rdoDangLam.isSelected()) {
                entity.setTrangThai(1);
            } else {
                entity.setTrangThai(0);
            }
            entity.setEmail(txtEmail.getText());
            nhanVienDAO.update(entity);
            fillToTable();
            JOptionPane.showMessageDialog(this, "Đã sửa thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTenSanPham;
    private javax.swing.JLabel lblTenSanPham1;
    private javax.swing.JLabel lblTenSanPham10;
    private javax.swing.JLabel lblTenSanPham2;
    private javax.swing.JLabel lblTenSanPham3;
    private javax.swing.JLabel lblTenSanPham4;
    private javax.swing.JLabel lblTenSanPham5;
    private javax.swing.JLabel lblTenSanPham6;
    private javax.swing.JLabel lblTenSanPham7;
    private javax.swing.JLabel lblTenSanPham8;
    private javax.swing.JLabel lblTenSanPham9;
    private javax.swing.JRadioButton rdoDangLam;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNghiLam;
    private javax.swing.JRadioButton rdoNhanVien;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JRadioButton rdoQuanLy;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtmatKhau;
    // End of variables declaration//GEN-END:variables

    @Override
    public void open() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void setForm(NhanVien entity) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public NhanVien getForm() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void fillToTable() {
        DefaultTableModel model = (DefaultTableModel) tblNhanVien.getModel();
        model.setRowCount(0);
        lstNhanVien = nhanVienDAO.findAll();
        for (NhanVien nhanVien : lstNhanVien) {
            Object[] row = {
                nhanVien.getId(),
                nhanVien.getMaNV(),
                nhanVien.getHoTen(),
                nhanVien.getGioiTinh() == 1 ? "Nam" : "Nữ",
                nhanVien.getNgaySinh(),
                nhanVien.getSdt(),
                nhanVien.getMatKhau(),
                nhanVien.getChucVu() == 1 ? "Quản lý" : "Nhân viên",
                nhanVien.getEmail(),
                nhanVien.getTrangThai() == 1 ? "Đang làm" : "Nghỉ làm"
            };
            model.addRow(row);
        }
    }

    @Override
    public void edit() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void create() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void update() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void delete() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void clear() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void setEditable(boolean editable) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void checkAll() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void uncheckAll() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void deleteCheckedItems() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void moveFirst() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void movePrevious() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void moveNext() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void moveLast() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void moveTo(int rowIndex) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

}
